### ISSUE TITLE
Charge a card token w/o a customer

### ISSUE THREAD

**Issue by lonnylot** [jlinn/stripe-api-php#24]
There does not seem to be any way to charge a card token that does not have a customer.

Before creating a PR I wanted to find out if you were open to having this in your lib.

**Comment by lesfleurs** [comment]
is it possible to create a charge request with just a card id?

**Comment by jlinn** [comment]
It doesn't look like it.  The [Stripe docs](https://stripe.com/docs/api#create_charge) indicate that a customer ID, card token, or full set of card data is required.
