### ISSUE TITLE
Listing entities

### ISSUE THREAD

**Issue by downsider** [jlinn/stripe-api-php#27]
Hi

Firstly, I have to say that thank you for writing this Stripe API. It blows the official API out of the water.

However, I noticed an issue with list operations; I'm not sure if it's a bug or a break in BC, but the parameters "count" and "offset" aren't used by the Stripe REST API. Stripe seems to use the format:
**limit**: number of records (analogous to "count")
**starting_after** / **ending_before**: these are record ids, used to page the results

Also, there are other filter parameters for specific records, like "customer" and "date" for listing invoices, which it would be really useful to have access to.

Do you have plans to implement these?

**Comment by jlinn** [comment]
Thanks for the kind words!  I don't write much php these days, so I hadn't planned on implementing support for those parameters.  That said, it shouldn't be difficult to do.  I'll see what I can work up over the next couple of days.

**Comment by jlinn** [comment]
With the release of [v1.2.0](https://github.com/jlinn/stripe-api-php/releases/tag/v1.2.0), all parameters for list requests are now supported.  
For example:

```php
$request = new ListRequest();
$request->setLimit(2);
$customers = $stripe->customers()->listCustomers($request);
```

Enjoy!

**Comment by downsider** [comment]
Thank you. That looks awesome :)
