### ISSUE TITLE
Retrieving customers

### ISSUE THREAD

**Issue by lesfleurs** [jlinn/stripe-api-php#29]
Currently using this with the stripe api in test mode and whenever i use the customers class to get a customer with a customer id, it does not return a default card or a list of cards associated with the customer, is this the default behaviour?

**Comment by jlinn** [comment]
No, it isn't.  The client library was using the old `cards` field when retrieving customer data.  This has been updated to use the new `sources` field in the [latest version](https://github.com/jlinn/stripe-api-php/releases/tag/v1.3.0).
